#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MASTER = ROOT / "MASTER_MILESTONE.md"
TASK_PATTERN = re.compile(
    r"<!-- MILESTONE: (?P<id>[A-Z0-9-]+) \| module: (?P<module>[^|]+) "
    r"\| status: (?P<status>[^|]+) \| priority: (?P<priority>[^ ]+) -->\n"
    r"(?P<body>.*?)(?=\n<!-- MILESTONE: |\Z)",
    re.DOTALL,
)
ALLOWED_STATUS = {"not_started", "in_progress", "blocked", "done"}
MODULE_PATHS = {
    "AGWallet": Path("AGWallet/MILESTONES.md"),
    "AetherAG": Path("AetherAG/MILESTONES.md"),
    "AetherShared": Path("AetherShared/MILESTONES.md"),
    "flow-swift-macos": Path("flow-swift-macos/MILESTONES.md"),
    "root": Path("MILESTONES.md"),
}

NON_GENERATED_MODULES = frozenset({
    # Nested repositories retain hand-maintained milestone histories. They remain
    # valid MASTER_MILESTONE.md modules but are never overwritten by root views.
    "AetherAG",
    "flow-swift-macos",
})

HEADER = """<!-- GENERATED FILE: DO NOT EDIT DIRECTLY.
Source: MASTER_MILESTONE.md
Regenerate: python3 scripts/sync_milestones.py
-->
"""

def parse_tasks(master_text: str):
    tasks = []
    for match in TASK_PATTERN.finditer(master_text):
        task = match.groupdict()
        task["module"] = task["module"].strip()
        task["status"] = task["status"].strip()
        task["priority"] = task["priority"].strip()
        task["body"] = task["body"].strip()
        if task["status"] not in ALLOWED_STATUS:
            raise ValueError(f"{task['id']}: unsupported status {task['status']!r}")
        if task["module"] not in MODULE_PATHS:
            raise ValueError(f"{task['id']}: unsupported module {task['module']!r}")
        tasks.append(task)
    if not tasks:
        raise ValueError("No milestone task markers found in MASTER_MILESTONE.md")
    ids = [task["id"] for task in tasks]
    duplicate_ids = sorted({task_id for task_id in ids if ids.count(task_id) > 1})
    if duplicate_ids:
        raise ValueError(f"Duplicate task IDs: {', '.join(duplicate_ids)}")
    return tasks

def render(module: str, tasks: list[dict]) -> str:
    totals = defaultdict(int)
    for task in tasks:
        totals[task["status"]] += 1
    lines = [
        HEADER.rstrip(),
        "",
        f"# {module} Milestones",
        "",
        "> Generated from the repository-root `MASTER_MILESTONE.md`.",
        "> Do not edit this file directly; edit the master and run the sync script.",
        "",
        "## Status",
        "",
        f"- Done: {totals['done']}",
        f"- In progress: {totals['in_progress']}",
        f"- Blocked: {totals['blocked']}",
        f"- Not started: {totals['not_started']}",
        "",
        "## Tasks",
        "",
    ]
    for task in tasks:
        lines.extend(
            [
                f"<!-- Source task: {task['id']} -->",
                f"### {task['id']} — {task['body'].splitlines()[0].replace('#### ', '')}",
                "",
                f"- **Status:** `{task['status']}`",
                f"- **Priority:** `{task['priority']}`",
                "",
                *[line.rstrip() for line in task["body"].splitlines()],
                "",
            ]
        )
    return "\n".join(line.rstrip() for line in lines).rstrip() + "\n"

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate module milestone views from MASTER_MILESTONE.md."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated module milestone files are stale.",
    )
    args = parser.parse_args()

    if not MASTER.exists():
        print(f"Missing {MASTER}", file=sys.stderr)
        return 2

    try:
        tasks = parse_tasks(MASTER.read_text(encoding="utf-8"))
    except ValueError as error:
        print(f"Milestone validation failed: {error}", file=sys.stderr)
        return 2

    grouped: dict[str, list[dict]] = defaultdict(list)
    for task in tasks:
        grouped[task["module"]].append(task)

    stale = []
    for module, relative_path in MODULE_PATHS.items():
        if module in NON_GENERATED_MODULES:
            continue
        content = render(module, grouped.get(module, []))
        destination = ROOT / relative_path
        existing = destination.read_text(encoding="utf-8") if destination.exists() else ""
        if existing != content:
            stale.append(str(relative_path))
            if not args.check:
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_text(content, encoding="utf-8")

    if stale and args.check:
        print("Generated milestone files are stale:")
        for path in stale:
            print(f"  - {path}")
        print("Run: python3 scripts/sync_milestones.py")
        return 1

    if stale:
        print("Updated generated milestone files:")
        for path in stale:
            print(f"  - {path}")
    else:
        print("Milestone views are current.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
